### ISSUE TITLE
Solution to i_introduction - Extensions On Collection is incorrect

### ISSUE THREAD

**Issue by RNabel** [vicboma1/Kotlin-Koans#2]
Hi there, first of all this page has been a great resource!

The solution to Extensions on Collections is listed in [the online tutorial](http://try.kotlinlang.org/#/Kotlin%20Koans/Introduction/Extensions%20on%20collections/Task.kt) as:

``` kotlin
arrayListOf(1, 5, 2).sortedDescending()
```

**Comment by vicboma1** [comment]
@RNabel, my solution for this test is as correct as your answer.
Thanks for your issue!
Greeting!!!

![screen shot 2016-11-14 at 18 59 38](https://cloud.githubusercontent.com/assets/3646388/20276451/93362dd4-aa9c-11e6-98d4-8ca3e242ede9.png)

**Comment by RNabel** [comment]
Great, thank you for having a look! While your answer is correct, the question states: 
"Rewrite the previous example once more using an extension function sortedDescending" :wink:
